lucky13/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, LoginView

import notifications.urls

from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', include('social_match.urls')),
    path('inactive_user/', views.inactive_user, name='inactive_user'),
    url(r'^friendship/', include('friendship.urls')),
    url('^inbox/notifications/', include(notifications.urls,namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_match/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django_filters.views import FilterView
from social_match.filters import UserFilter
from .models import *

app_name = 'social_match'
urlpatterns = [
	path('', views.base, name='base'),
	path('about/', views.about, name='about'),
	path('home/', views.home, name='home'),
	url(r'^search/$', FilterView.as_view(filterset_class=UserFilter,
										 template_name='social_match/search.html'), name='search'),
	path('search/', views.resetsearch, name='resetsearch'),
	path('createpost/', views.createpost, name='createpost'),
	path('profile/', views.profile, name='profile'),
	path('profile/<int:user_id>/', views.profile, name='profile'),
	path('editprofile/<int:user_id>/', views.editprofile, name="editprofile"),
    #path('follow/<int:user_id>/', views.follow, name='follow'),
    path('follow/', views.follow, name='follow'),
	#path('unfollow/<int:user_id>/', views.unfollow, name='unfollow'),
    path('unfollow/', views.unfollow, name='unfollow'),
    path('following/', views.following, name='following'),
    path('follower/', views.follower, name='follower'),
    #path('block/<int:user_id>/', views.block, name='block'),
    path('block/', views.block, name='block'),
	#path('unblock/<int:user_id>/', views.unblock, name='unblock'),
    path('unblock/', views.unblock, name='unblock'),
	path('likepost/', views.likepost, name="likepost"),
	path('commentpost/', views.commentpost, name="commentpost"),
	path('notifications/', views.notifications, name="notifications"),
	path('editpost/<int:post_id>/', views.editpost, name="editpost"),
	path('api/classes/', views.classlist, name='classlist'),
	path('api/majors/', views.majorlist, name='majorlist'),
	path('api/minors/', views.minorlist, name='minorlist'),
	path("api/major-autocomplete/", views.MajorAutocomplete.as_view(), name='major-autocomplete'),
	path("api/minor-autocomplete/", views.MinorAutocomplete.as_view(), name='minor-autocomplete'),
	path("api/course-autocomplete/", views.CourseAutocomplete.as_view(), name='course-autocomplete'),
	path("api/skill-autocomplete/", views.SkillAutocomplete.as_view(model=Skill, create_field='name'), name='skill-autocomplete'),
	path("api/activity-autocomplete/", views.ActivityAutocomplete.as_view(model=Activity, create_field='name'),
		 name='activity-autocomplete'),
	path("api/interest-autocomplete/", views.InterestAutocomplete.as_view(model=Interest, create_field='name'),
		 name='interest-autocomplete'),

	# separate paths for autocomplete without option to create (for searching)
	path("api/skill-autocomplete-search/", views.SkillAutocomplete.as_view(model=Skill), name='skill-search'),
	path("api/activity-autocomplete-search/", views.ActivityAutocomplete.as_view(model=Activity),
		 name='activity-search'),
	path("api/interest-autocomplete-search/", views.InterestAutocomplete.as_view(model=Interest),
		 name='interest-search'),
]

social_match/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.utils import timezone
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.templatetags.static import static
from lucky13 import settings
import os.path

class Major(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Minor(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Course(models.Model):
    department = models.CharField(max_length=10) # abbreviation of department, usually found with course number
    number = models.IntegerField(validators=[MaxValueValidator(9999), MinValueValidator(100)])
    name = models.CharField(max_length=200)
    def __str__(self):
        return "{} {}: {}".format(self.department, self.number, self.name)


class Skill(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Interest(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Activity(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Activities" # this appears on the admin menu


# helper functions to get correct graduation year options
def current_year():
    return datetime.date.today().year


def min_value_current_year(value):
    return MinValueValidator(current_year())(value)


def max_value_in_four_years(value):
    return MaxValueValidator(current_year()+4)(value)

class User(AbstractUser):
    # define adjustable status (is_active is always true)
    status_active = models.BooleanField(default=True)

    phone_regex = RegexValidator(regex=r'^\+\d{8,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex], max_length=16, blank=True)

    # define choices for class standing
    first_year = '1st'
    second_year = '2nd'
    third_year = '3rd'
    fourth_year = '4th'
    graduate = '5th'
    class_standing_choices = (
        (first_year, 'First Year'),
        (second_year, 'Second Year'),
        (third_year, 'Third Year'),
        (fourth_year, 'Fourth Year'),
        (graduate, 'Graduate'),
    )
    class_standing = models.CharField(
        max_length=3,
        choices=class_standing_choices,
        default=first_year
    )

    graduation_year = models.PositiveIntegerField(default=current_year()+4, validators=[min_value_current_year, max_value_in_four_years])
    picture = models.ImageField(blank=True, upload_to='images/')
    majors = models.ManyToManyField(Major, blank=True)
    minors = models.ManyToManyField(Minor, blank=True)
    skills = models.ManyToManyField(Skill, blank=True)
    interests = models.ManyToManyField(Interest, blank=True)
    courses = models.ManyToManyField(Course, blank=True)
    activities = models.ManyToManyField(Activity, blank=True)

    # identify if picture is not set or is missing and return url of default profile picture
    @property
    def valid_picture_url(self):
        if self.picture:
            dir = settings.BASE_DIR
            if not os.path.isfile(dir + self.picture.url):
                return False
            else:
                return True
        else:
            return False



    def __str__(self):			# error in admin
        return str(self.username) # computing ID

    # potential saved users/friends field can be added later (ManyToManyField or ForeignKey)
    # consider using django-friendship or other open source apps to implement relationships between Users

    # posts (like a blog) can be added here as a ManyToManyField, referencing a separate Post model

class Post(models.Model):
    post_active = models.BooleanField(default=True)
    post_edited = models.BooleanField(default=False)

    headline = models.CharField(max_length=50)
    message = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField('date posted', blank=True)
    date_edited = models.DateTimeField('date edited', blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    def __str__(self):
        return self.headline

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', blank=True)
    text = models.CharField(max_length=250)
    date = models.DateTimeField('date commented', blank=True)

    def __str__(self):
        return self.text

social_match/forms.py
from django import forms
from .models import *
from dal import autocomplete


class PostForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ('headline', 'message')

class EditPostForm(forms.ModelForm):
    post_active = forms.BooleanField(required=False)
    message = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = {'headline', 'message', 'post_active'}

class CommentPostForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.TextInput(attrs={
                'id': 'comment-text',
                'required': True,
            })
        }


class PostSearchForm(forms.Form):
    name = forms.CharField(max_length=50, required=False)
    keywords = forms.CharField(max_length=200, required=False)
    following = forms.BooleanField(required=False)
    liked = forms.BooleanField(required=False)
    commented = forms.BooleanField(required=False)

class EditProfileForm(forms.ModelForm):
    status_active = forms.BooleanField(required=False)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone',
		  'class_standing', 'graduation_year',
                  'majors', 'minors', 'skills',
                  'interests', 'courses', 'activities', 'picture')
        widgets = {
            'majors': autocomplete.ModelSelect2Multiple(
                url='social_match:major-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'minors': autocomplete.ModelSelect2Multiple(
                url='social_match:minor-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'courses': autocomplete.ModelSelect2Multiple(
                url='social_match:course-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'skills': autocomplete.ModelSelect2Multiple(
                url='social_match:skill-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'activities': autocomplete.ModelSelect2Multiple(
                url='social_match:activity-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'interests': autocomplete.ModelSelect2Multiple(
                url='social_match:interest-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            )
        }

class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
             if field_name in self.initial:
                field.initial = self.initial[field_name]

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'graduation_year', 'class_standing', 'picture', 
		  'majors', 'minors', 'skills', 'interests', 'courses', 'activities',)

social_match/templates/social_match/follow_block.html
{% load static %}

<div align="center">
            {% if not check_follow %}
                {% comment %}
                <a href="{% url 'social_match:follow' viewing_user.id %}" method="post" id="follow" name="follow" data-u="{{viewing_user.id}}"><button type="button" class="btn btn-info">Follow</button></a>
                {% endcomment %}
                <a href="{% url 'social_match:follow' %}" method="post" id="follow" name="follow" data-u="{{viewing_user.id}}" data-b="{{check_block}}"><button type="button" class="btn btn-info">Follow</button></a>
            {% elif check_follow %}
                {% comment %}
                <a href="{% url 'social_match:unfollow' viewing_user.id %}" method="post" id="unfollow" name="unfollow"><button type="button" class="btn btn-info">Unfollow</button></a>
                {% endcomment %}
                <a href="{% url 'social_match:unfollow' %}" method="post" id="unfollow" name="unfollow" data-u="{{viewing_user.id}}" data-b="{{check_block}}"><button type="button" class="btn btn-info">Unfollow</button></a>
            {% endif %}

            {% if not check_block %}
                {% comment %}
                <a href="{% url 'social_match:block' viewing_user.id %}" method="post" id="block" name="block"><button type="button" class="btn btn-info">Block</button></a>
                {% endcomment %}
                <a href="{% url 'social_match:block' %}" method="post" id="block" name="block" data-u="{{viewing_user.id}}" data-f="{{check_follow}}"><button type="button" class="btn btn-info">Block</button></a>
            {% elif check_block %}
                {% comment %}
                <a href="{% url 'social_match:unblock' viewing_user.id %}" method="post" id="unblock" name="unblock"><button type="button" class="btn btn-info">Unblock</button></a>
                {% endcomment %}
                <a href="{% url 'social_match:unblock' %}" method="post" id="unblock" name="unblock" data-u="{{viewing_user.id}}" data-f="{{check_follow}}"><button type="button" class="btn btn-info">Unblock</button></a>
            {% endif %}
            </div>

social_match/templates/social_match/follower.html
{% extends 'social_match/base.html' %}
{% load static %}
{% load friendshiptags %}
{% block content %}

<p>Followers: </p>
<p>{% followers request.user %}</p>

{% endblock %}

social_match/templates/social_match/following.html
{% extends 'social_match/base.html' %}
{% load static %}
{% load friendshiptags %}
{% block content %}

<p>Following: </p>
<p>{% following request.user %}</p>

{% endblock %}

social_match/templates/social_match/home_posts.html
{% load static %}

<div>
    {% if filtered %}
        <h3>Showing filter results for:</h3>
        <h5>
        name: {{ names }} <br>
        keywords: {{ keywords }} <br>
        posts liked: {{ liked }} <br>
        posts commented on: {{ commented }} <br><br>
        </h5>
    {% else %}
        <h3>All Posts</h3><br>
    {% endif %}
    {% if post_list %}
    {% for post in post_list %}
{#    <div class="card" style="width: 35rem;">#}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title" style="display:inline">{{ post.headline }}</h5>
            {% if post.user == user %}
            <a class ="btn-md" style="margin-left:20px;" href="{% url 'social_match:editpost' post.id %}">
                    <i class="fas fa-edit"></i></i>
            </a><br>
            {% endif %}
            <a href="{% url 'social_match:profile' post.user.id %}" class="primary">{{post.user.first_name}} {{post.user.last_name}}</a>

        </div>
        <div class="card-body">
            <p>{{ post.message }}</p>
        </div>
        <div class="card-footer">

            <p style="float:left">{{ post.likes.count }} like{{ post.likes.count|pluralize }}</p>
            {% if post.post_edited %}
                <p style="float:right">Edited {{ post.date_edited }}</p>
            {% else %}
                <p style="float:right">Posted {{ post.date }}</p>
            {% endif %}

            <div style="clear: both;"></div>
{#        </div>#}
{#        <div style="display:flex;">#}
            <form style="display:inline" action="{% url 'social_match:likepost' %}" method="post">
                {% csrf_token %}
                {% if user in post.likes.all %}
                <button type="submit" id="like-home" value="{{post.id}}" data-t="home" data-p="{{post_list.number}}" data-k="{{keywords}}" data-n="{{names}}" data-l="{{liked}}" data-c="{{commented}}" data-f="{{filtered}}" class="btn btn-outline-primary btn-rounded waves-effect btn-md"><i class="fas fa-thumbs-down"></i></button>
                {% else %}
                    <button type="submit" id="like-home" value="{{post.id}}" data-t="home" data-p="{{post_list.number}}" data-k="{{keywords}}" data-n="{{names}}" data-l="{{liked}}" data-c="{{commented}}" data-f="{{filtered}}" class="btn btn-primary btn-md"><i class="fas fa-thumbs-up"></i></button>
                {% endif %}
            </form>

            {% if form != None and post_id == post.id %}
                <form style="display:inline" action = "{% url 'social_match:commentpost' %}" method="post" id="comment-form">
                {% csrf_token %}
                {{ form.text }}
                <button type="submit" id="submitcomment-home" value="{{post.id}}" data-t="home" data-p="{{post_list.number}}" data-k="{{keywords}}" data-n="{{names}}" data-l="{{liked}}" data-c="{{commented}}" data-f="{{filtered}}" class="btn btn-outline-primary btn-rounded waves-effect btn-md"><i class="fas fa-comment"></i></button>
                </form>
            {% else %}
                <form style="display:inline" action="{% url 'social_match:commentpost' %}" method="post">
                {% csrf_token %}
                <button type="submit" id="comment-home" value="{{post.id}}" data-t="home" data-p="{{post_list.number}}" data-k="{{keywords}}" data-n="{{names}}" data-l="{{liked}}" data-c="{{commented}}" data-f="{{filtered}}" class="btn btn-primary btn-md"><i class="fas fa-comment"></i></button>
                </form>
            {% endif %}
        </div>

        <ul class="list-group list-group-flush">
            {% for comment in post.comments.all %}
            <li class="list-group-item"><p><a href="{% url 'social_match:profile' comment.user.id %}" class="primary">{{ comment.user.first_name }} {{ comment.user.last_name }}</a>: {{ comment.text }}
                <br><font size ='1'>{{ comment.date }}</font>
                {% if request.user == comment.user %}
                <a href="{% url 'social_match:commentpost' %}" method="post" id="deletecomment-home" data-cid="{{comment.id}}" data-t="home" data-p="{{post_list.number}}" data-k="{{keywords}}" data-n="{{names}}" data-l="{{liked}}" data-c="{{commented}}" data-f="{{filtered}}" class="primary">
                    <i class="fas fa-trash"></i></a>
                {% endif %}
            </p></li>
            {% endfor %}
        </ul>



    </div>
    <br>
    {% endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if post_list.has_previous %}
                    <a href="?p=1&k={{keywords}}&n={{names}}&l={{liked}}&c={{commented}}&f={{filtered}}" class="primary">&laquo; first</a> -
                    {% if post_list.previous_page_number != 1 %}
                        <a href="?p={{post_list.previous_page_number}}&k={{keywords}}&n={{names}}&l={{liked}}&c={{commented}}&f={{filtered}}" class="primary">previous</a>
                    {% endif %}
                {% endif %}

                <span class="current">
                    Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
                </span>

                {% if post_list.has_next %}
                    {% if post_list.next_page_number != post_list.paginator.num_pages %}
                        <a href="?p={{post_list.next_page_number}}&k={{keywords}}&n={{names}}&l={{liked}}&c={{commented}}&f={{filtered}}" class="primary">next</a> -
                    {% endif %}
                <a href="?p={{post_list.paginator.num_pages}}&k={{keywords}}&n={{names}}&l={{liked}}&c={{commented}}&f={{filtered}}" class="primary">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% else %}
    <p>No posts are available.</p>
    {% endif %}
</div>

social_match/templates/social_match/profile.html
{% extends 'social_match/base.html' %}
{% load static %}
{% block content %}
{% load friendshiptags %}
{% load socialmatchtags %}
{% if viewing_user.is_authenticated %}


<div class="container">
    <div class="row">
        <div class="col-md-4 col-sm-12 mb-3">
                {% if viewing_user.valid_picture_url %}
{#                    {% if viewing_user.picture.isempty or viewing_user.picture.name == 'False' %}#}
{#                        <img style='display: block; margin: auto;' height='256' width='256' src="{% static 'images/Portrait_Placeholder_Square.png' %}">#}
{#                    {% else %}#}
                        <img style='display: block; margin: auto;' height='256' width='256' src="{{ viewing_user.picture.url }}">
{#                    {% endif %}#}
                {% else %}
                    <img style='display: block; margin: auto;' height='256' width='256' src="{% static 'images/Portrait_Placeholder_Square.png' %}">
{#                    <i class="fas fa-viewing_user fa-10x img-thumbnail"></i>#}
                {% endif %}

            <br />
        {% if viewing_user == user %}
            <div align="center">
                <form action="{% url 'social_match:editprofile' user.id %}" method="GET">
                    {% csrf_token %}
                    <input class="btn btn-light" type="submit" value="Edit Profile" name="edit_profile">
                </form>
            </div>
            <div>

                    
                    {% comment %} <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="file" name="myfile">
                        <button class="btn btn-light" type="submit">Upload</button>
                    </form>

                        {% if uploaded_file_url %}
                            <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
                        {% endif %} {% endcomment %}
            </div>
            <div align="center">
                <div>Following:<a data-toggle="modal" data-target="#followingModal" style="color:blue"> {{ following|length}} user{{ following|pluralize }}.</a></div>
                <div>Blocking:<a data-toggle="modal" data-target="#blockingModal" style="color:blue"> {{ blocking|length }} user{{ blocking|pluralize }}.</a></div>
            </div>
        {% else %}
            {% comment %}
            <div align="center">
            {% if not check_follow %}
                <a href="{% url 'social_match:follow' viewing_user.id %}" method="post" id="follow" name="follow" data-u="{{viewing_user.id}}"><button type="button" class="btn btn-info">Follow</button></a>
            {% elif check_follow %}
                <a href="{% url 'social_match:unfollow' viewing_user.id %}" method="post" id="unfollow" name="unfollow"><button type="button" class="btn btn-info">Unfollow</button></a>
            {% endif %}

            {% if not check_block %}
                <a href="{% url 'social_match:block' viewing_user.id %}" method="post" id="block" name="block"><button type="button" class="btn btn-info">Block</button></a>
            {% elif check_block %}
                <a href="{% url 'social_match:unblock' viewing_user.id %}" method="post" id="unblock" name="unblock"><button type="button" class="btn btn-info">Unblock</button></a>
            {% endif %}
            </div>
            {% endcomment %}
            <div id="follow_block">
                {% include 'social_match/follow_block.html' %}
            </div>
        {% endif %}
        </div>

        
            <div class="col-md-8 col-sm-12 mb-3">
                <div class="info" style="display:none">
                    <h4 class="display-4">{{ viewing_user.first_name }} {{ viewing_user.last_name }}</h4>
                </div>
                <div class="info2" style="display:none">
                <h5><strong>{% if viewing_user.class_standing %} {{ viewing_user.get_class_standing_display }}, {% endif %}Class of {{ viewing_user.graduation_year }}</strong></h5>
                <h5><strong>Majors: </strong>
                    {% for major in viewing_user.majors.all %}
                        {% if forloop.last %}
                            {{ major.name }}
                        {% else %}
                            {{ major.name }},
                        {% endif %}
                    {% endfor %}
                </h5>
                <h5><strong>Minors: </strong>
                    {% for minor in viewing_user.minors.all %}
                        {% if forloop.last %}
                            {{ minor.name }}
                        {% else %}
                            {{ minor.name }},
                        {% endif %}
                    {% endfor %}
                </h5>
                <h5><strong>Courses: </strong>
                    {% for course in viewing_user.courses.all %}
                        {% if forloop.last %}
                            {{ course.name }}
                        {% else %}
                            {{ course.name }},
                        {% endif %}
                    {% endfor %}
                </h5>
                <h5><strong>Skills: </strong>
                    {% for skill in viewing_user.skills.all %}
                        {% if forloop.last %}
                            {{ skill.name }}
                        {% else %}
                            {{ skill.name }},
                        {% endif %}
                    {% endfor %}
                </h5>
                <h5><strong>Interests: </strong>
                    {% for interest in viewing_user.interests.all %}
                        {% if forloop.last %}
                            {{ interest.name }}
                        {% else %}
                            {{ interest.name }},
                        {% endif %}
                    {% endfor %}
                </h5>
                <h5><strong>Activities: </strong>
                    {% for activity in viewing_user.activities.all %}
                        {% if forloop.last %}
                            {{ activity.name }}
                        {% else %}
                            {{ activity.name }},
                        {% endif %}
                    {% endfor %}
                </h5>


            <hr>
                <h4 class="display-5"><strong>Contact: </strong></h4>
                <h5><strong>Email: </strong> {{ viewing_user.email }}</h5>
                <h5><strong>Phone: </strong> {{ viewing_user.phone }}</h5>
                </div>

            <br />

        </div>
    </div>

    <hr>
    <div id="profile_posts">
        {% include 'social_match/posts_ajax/profile_posts.html' %}
    </div>

</div>

{% comment %} Following Modal {% endcomment %}
<div class="modal fade" id="followingModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">People Who You Are Following:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          {% following_list request.user as following %}
          <div>
              {% if following %}
              <ul>
                {% for user in following %}
                    <div class="row">
                        <div class="card card2" style="width:93%">
                            <div class="card-body" style="display:flex;">
                                <h5 class="card-title" style="display: flex;">
                                    {% if user.valid_picture_url %}
                                        <img height='20' width='20' src="{{ user.picture.url }}">
                                    {% else %}
                                        <img height='20' width='20' src="{% static 'images/Portrait_Placeholder_Square.png' %}">
                                    {% endif %}
                                </h5>
                                <a style="margin-left:20px" href="{% url 'social_match:profile' user.id %}" class="primary">{{user.first_name}} {{user.last_name}}</a>
                                <p style="margin-left:20px" class="card-text">{% if user.class_standing %} {{ user.get_class_standing_display }}, {% endif %}Class of {{ user.graduation_year }}</p>

                            </div>
                        </div>
                    </div>
                {% endfor %}
                  </ul>
              {% else %}
                You are not following anyone.
              {% endif %}
          </div>
      </div>
    </div>
  </div>
</div>

{% comment %} Blocking Modal {% endcomment %}
<div class="modal fade" id="blockingModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">People Who You Have Blocked:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          {% blocking_list request.user as blocking%}
          <div>
              {% if blocking %}
                <ul>
                {% for user in blocking %}
                    <div class="row">
                        <div class="card card2" style="width:93%">
                            <div class="card-body" style="display:flex">
                                <h5 class="card-title" style="display: flex">
                                    {% if user.valid_picture_url %}
                                        <img height='20' width='20' src="{{ user.picture.url }}">
                                    {% else %}
                                        <img height='20' width='20' src="{% static 'images/Portrait_Placeholder_Square.png' %}">
                                    {% endif %}
                                </h5>
                                <a style="margin-left:20px" href="{% url 'social_match:profile' user.id %}" class="primary">{{user.first_name}} {{user.last_name}}</a>
                                <p style="margin-left:20px" class="card-text">{% if user.class_standing %} {{ user.get_class_standing_display }}, {% endif %}Class of {{ user.graduation_year }}</p>

                            </div>
                        </div>
                    </div>
                {% endfor %}
                </ul>
              {% else %}
                You are not blocking anyone.
              {% endif %}
          </div>
      </div>
    </div>
  </div>
</div>

{% endif %}
{% endblock %}