lucky13/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, LoginView

import notifications.urls

from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', include('social_match.urls')),
    path('inactive_user/', views.inactive_user, name='inactive_user'),
    url(r'^friendship/', include('friendship.urls')),
    url('^inbox/notifications/', include(notifications.urls,namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_match/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django_filters.views import FilterView
from social_match.filters import UserFilter
from .models import *

app_name = 'social_match'
urlpatterns = [
	path('', views.base, name='base'),
	path('about/', views.about, name='about'),
	path('home/', views.home, name='home'),
	url(r'^search/$', FilterView.as_view(filterset_class=UserFilter,
										 template_name='social_match/search.html'), name='search'),
	path('search/', views.resetsearch, name='resetsearch'),
	path('createpost/', views.createpost, name='createpost'),
	path('profile/', views.profile, name='profile'),
	path('profile/<int:user_id>/', views.profile, name='profile'),
	path('editprofile/<int:user_id>/', views.editprofile, name="editprofile"),
    #path('follow/<int:user_id>/', views.follow, name='follow'),
    path('follow/', views.follow, name='follow'),
	#path('unfollow/<int:user_id>/', views.unfollow, name='unfollow'),
    path('unfollow/', views.unfollow, name='unfollow'),
    path('following/', views.following, name='following'),
    path('follower/', views.follower, name='follower'),
    #path('block/<int:user_id>/', views.block, name='block'),
    path('block/', views.block, name='block'),
	#path('unblock/<int:user_id>/', views.unblock, name='unblock'),
    path('unblock/', views.unblock, name='unblock'),
	path('likepost/', views.likepost, name="likepost"),
	path('commentpost/', views.commentpost, name="commentpost"),
	path('notifications/', views.notifications, name="notifications"),
	path('editpost/<int:post_id>/', views.editpost, name="editpost"),
	path('api/classes/', views.classlist, name='classlist'),
	path('api/majors/', views.majorlist, name='majorlist'),
	path('api/minors/', views.minorlist, name='minorlist'),
	path("api/major-autocomplete/", views.MajorAutocomplete.as_view(), name='major-autocomplete'),
	path("api/minor-autocomplete/", views.MinorAutocomplete.as_view(), name='minor-autocomplete'),
	path("api/course-autocomplete/", views.CourseAutocomplete.as_view(), name='course-autocomplete'),
	path("api/skill-autocomplete/", views.SkillAutocomplete.as_view(model=Skill, create_field='name'), name='skill-autocomplete'),
	path("api/activity-autocomplete/", views.ActivityAutocomplete.as_view(model=Activity, create_field='name'),
		 name='activity-autocomplete'),
	path("api/interest-autocomplete/", views.InterestAutocomplete.as_view(model=Interest, create_field='name'),
		 name='interest-autocomplete'),

	# separate paths for autocomplete without option to create (for searching)
	path("api/skill-autocomplete-search/", views.SkillAutocomplete.as_view(model=Skill), name='skill-search'),
	path("api/activity-autocomplete-search/", views.ActivityAutocomplete.as_view(model=Activity),
		 name='activity-search'),
	path("api/interest-autocomplete-search/", views.InterestAutocomplete.as_view(model=Interest),
		 name='interest-search'),
]

social_match/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.utils import timezone
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.templatetags.static import static
from lucky13 import settings
import os.path

class Major(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Minor(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Course(models.Model):
    department = models.CharField(max_length=10) # abbreviation of department, usually found with course number
    number = models.IntegerField(validators=[MaxValueValidator(9999), MinValueValidator(100)])
    name = models.CharField(max_length=200)
    def __str__(self):
        return "{} {}: {}".format(self.department, self.number, self.name)


class Skill(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Interest(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Activity(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Activities" # this appears on the admin menu


# helper functions to get correct graduation year options
def current_year():
    return datetime.date.today().year


def min_value_current_year(value):
    return MinValueValidator(current_year())(value)


def max_value_in_four_years(value):
    return MaxValueValidator(current_year()+4)(value)

class User(AbstractUser):
    # define adjustable status (is_active is always true)
    status_active = models.BooleanField(default=True)

    phone_regex = RegexValidator(regex=r'^\+\d{8,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex], max_length=16, blank=True)

    # define choices for class standing
    first_year = '1st'
    second_year = '2nd'
    third_year = '3rd'
    fourth_year = '4th'
    graduate = '5th'
    class_standing_choices = (
        (first_year, 'First Year'),
        (second_year, 'Second Year'),
        (third_year, 'Third Year'),
        (fourth_year, 'Fourth Year'),
        (graduate, 'Graduate'),
    )
    class_standing = models.CharField(
        max_length=3,
        choices=class_standing_choices,
        default=first_year
    )

    graduation_year = models.PositiveIntegerField(default=current_year()+4, validators=[min_value_current_year, max_value_in_four_years])
    picture = models.ImageField(blank=True, upload_to='images/')
    majors = models.ManyToManyField(Major, blank=True)
    minors = models.ManyToManyField(Minor, blank=True)
    skills = models.ManyToManyField(Skill, blank=True)
    interests = models.ManyToManyField(Interest, blank=True)
    courses = models.ManyToManyField(Course, blank=True)
    activities = models.ManyToManyField(Activity, blank=True)

    # identify if picture is not set or is missing and return url of default profile picture
    @property
    def valid_picture_url(self):
        if self.picture:
            dir = settings.BASE_DIR
            if not os.path.isfile(dir + self.picture.url):
                return False
            else:
                return True
        else:
            return False



    def __str__(self):			# error in admin
        return str(self.username) # computing ID

    # potential saved users/friends field can be added later (ManyToManyField or ForeignKey)
    # consider using django-friendship or other open source apps to implement relationships between Users

    # posts (like a blog) can be added here as a ManyToManyField, referencing a separate Post model

class Post(models.Model):
    post_active = models.BooleanField(default=True)
    post_edited = models.BooleanField(default=False)

    headline = models.CharField(max_length=50)
    message = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField('date posted', blank=True)
    date_edited = models.DateTimeField('date edited', blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    def __str__(self):
        return self.headline

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', blank=True)
    text = models.CharField(max_length=250)
    date = models.DateTimeField('date commented', blank=True)

    def __str__(self):
        return self.text

social_match/forms.py
from django import forms
from .models import *
from dal import autocomplete


class PostForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ('headline', 'message')

class EditPostForm(forms.ModelForm):
    post_active = forms.BooleanField(required=False)
    message = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = {'headline', 'message', 'post_active'}

class CommentPostForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.TextInput(attrs={
                'id': 'comment-text',
                'required': True,
            })
        }


class PostSearchForm(forms.Form):
    name = forms.CharField(max_length=50, required=False)
    keywords = forms.CharField(max_length=200, required=False)
    following = forms.BooleanField(required=False)
    liked = forms.BooleanField(required=False)
    commented = forms.BooleanField(required=False)

class EditProfileForm(forms.ModelForm):
    status_active = forms.BooleanField(required=False)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone',
		  'class_standing', 'graduation_year',
                  'majors', 'minors', 'skills',
                  'interests', 'courses', 'activities', 'picture')
        widgets = {
            'majors': autocomplete.ModelSelect2Multiple(
                url='social_match:major-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'minors': autocomplete.ModelSelect2Multiple(
                url='social_match:minor-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'courses': autocomplete.ModelSelect2Multiple(
                url='social_match:course-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'skills': autocomplete.ModelSelect2Multiple(
                url='social_match:skill-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'activities': autocomplete.ModelSelect2Multiple(
                url='social_match:activity-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            ),
            'interests': autocomplete.ModelSelect2Multiple(
                url='social_match:interest-autocomplete',
                attrs={
                    'style': 'width:100%',
                    'data-theme': 'bootstrap'
                },
            )
        }

class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
             if field_name in self.initial:
                field.initial = self.initial[field_name]

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'graduation_year', 'class_standing', 'picture', 
		  'majors', 'minors', 'skills', 'interests', 'courses', 'activities',)

social_match/templates/social_match/posts_ajax/profile_posts.html
{% load static %}
{% load widget_tweaks %}
{% load socialmatchtags %}

<div align="center">
        <h3 class="display-4">Posts:</h3>
        {% if post_list %}
        {% for post in post_list %}
        {% if viewing_user == user or post.post_active %}
            <div class="card" align="left">
                <div class="card-header">
                    <div class="row no-gutters">
                        <div class="col-1">
                            {% if post.user.valid_picture_url %}
                                <img class="img-fluid" src="{{ post.user.picture.url }}">
                            {% else %}
                                <img class="img-fluid" src="{% static 'images/Portrait_Placeholder_Square.png' %}">
                            {% endif %}
                        </div>
                        <div class="col-11 pl-2">
                            <h4 class="card-title" style="display:inline">
                                {% if not post.post_active %}
                                    <span class="badge badge-info">Archived</span><br>
                                {% endif %}
                                <strong>{{ post.headline }}</strong>

                            </h4>
                            {% if post.user == user %}
                            <a class ="btn-md" style="margin-left:20px;" href="/editpost/{{post.id}}?return=profile">
                                    <i class="fas fa-edit"></i></i>
                            </a>
                            {% endif %}
                            <br>
                            <a href="{% url 'social_match:profile' post.user.id %}" class="primary">{{post.user.first_name}} {{post.user.last_name}}</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <p class="lead">{{ post.message }}</p>
                </div>

                <div class="card-footer">
                    <a data-toggle="modal" data-target="#a{{post.id}}" style="color: blue">
                        <p style="float:left">{{ post.likes.count }} like{{ post.likes.count|pluralize }}</p>
                    </a>
                    {% if post.post_edited %}
                        <p style="float:right">Edited {{ post.date_edited }}</p>
                    {% else %}
                        <p style="float:right">Posted {{ post.date }}</p>
                    {% endif %}

                    <div style="clear: both;"></div>

                    <form style="display:inline" action="{% url 'social_match:likepost' %}" method="post">
                        {% csrf_token %}
                        {% if user in post.likes.all %}
                        <button type="submit" id="like-profile" value="{{post.id}}" data-t="profile" data-u="{{viewing_user.id}}" data-p="{{post_list.number}}" class="btn btn-outline-primary btn-rounded waves-effect btn-md"><i class="fas fa-thumbs-down"></i></button>
                        {% else %}
                              <button type="submit" id="like-profile" value="{{post.id}}" data-t="profile" data-u="{{viewing_user.id}}" data-p="{{post_list.number}}" class="btn btn-primary btn-md"><i class="fas fa-thumbs-up"></i></button>
                        {% endif %}
                    </form>

                    {% if form != None and post_id == post.id %}
                        <form style="display:inline" action = "{% url 'social_match:commentpost' %}" method="post" id="comment-form">
                        {% csrf_token %}
                        {% render_field form.text %}
                        <button type="submit" id="submitcomment-profile" value="{{post.id}}" data-t="profile" data-u="{{viewing_user.id}}" data-p="{{post_list.number}}" class="btn btn-outline-primary btn-rounded waves-effect btn-md"><i class="fas fa-comment"></i></button>
                        </form>
                    {% else %}
                        <form style="display:inline" action="{% url 'social_match:commentpost' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" id="comment-profile" value="{{post.id}}" data-t="profile" data-u="{{viewing_user.id}}" data-p="{{post_list.number}}" class="btn btn-primary btn-md"><i class="fas fa-comment"></i></button>
                        </form>
                    {% endif %}
                </div>

                 {% comment %} Likes Modal! {% endcomment %}
                <div class="modal fade" id="a{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">People Who Liked This Post:</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-body" style="overflow: auto;">
                                <div class="container">
                                    {% if post.likes.all %}
                                {% for user in post.likes.all %}
                                    <div class="row">
                                         <div class="card card2" style="width:100%">
                                            <div class="card-body" style="display:flex">
                                                <h5 class="card-title" style="display: flex">
                                                    {% if user.valid_picture_url %}
                                                        <img height='20' width='20' src="{{ user.picture.url }}">
                                                    {% else %}
                                                        <img height='20' width='20' src="{% static 'images/Portrait_Placeholder_Square.png' %}">
                                                    {% endif %}
                                                </h5>
                                                <a style="margin-left:20px" href="{% url 'social_match:profile' user.id %}" class="primary">{{user.first_name}} {{user.last_name}}</a>
                                                <p style="margin-left:20px" class="card-text">{% if user.class_standing %} {{ user.get_class_standing_display }}, {% endif %}Class of {{ user.graduation_year }}</p>

                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                {% else %}
                                    No likes yet!
                                {% endif %}
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% comment %} End of Modal! {% endcomment %}

                <ul class="list-group list-group-flush">
                    {% post_comments post as comments %}

                    {% for comment in comments %}
                        <li class="list-group-item">
                            <div class="row no-gutters">
                                <div class="col-1">
                                    <div style="max-width: 50px;">
                                        {% if comment.user.valid_picture_url %}
                                            <img class="img-fluid" src="{{ comment.user.picture.url }}">
                                        {% else %}
                                            <img class="img-fluid" src="{% static 'images/Portrait_Placeholder_Square.png' %}">
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-11 pl-2">
                                    <p>
                                    <a href="{% url 'social_match:profile' comment.user.id %}" class="primary">{{ comment.user.first_name }} {{ comment.user.last_name }}</a>: {{ comment.text }}
                                        <br>
                                        <span class="card-info">{{ comment.date }}</span>
                                        {% if request.user == comment.user %}
                                            <a href="{% url 'social_match:commentpost' %}" method="post" id="deletecomment-profile" data-cid="{{comment.id}}" data-t="profile" data-p="{{post_list.number}}" data-k="{{keywords}}" data-n="{{names}}" data-l="{{liked}}" data-c="{{commented}}" data-f="{{filtered}}" class="primary">
                                                <i class="fas fa-trash"></i></a>
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>

            </div>
        {% endif %}
            <br>
        {% endfor %}
        <div class="pagination">
            <span class="step-links">
                {% if post_list.has_previous %}
                    <a href="?p=1" class="primary">&laquo; first</a> -
                    {% if post_list.previous_page_number != 1 %}
                        <a href="?p={{post_list.previous_page_number}}" class="primary">previous</a>
                    {% endif %}
                {% endif %}

                <span class="current">
                    Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
                </span>

                {% if post_list.has_next %}
                    {% if post_list.next_page_number != post_list.paginator.num_pages %}
                        <a href="?p={{post_list.next_page_number}}" class="primary">next</a> -
                    {% endif %}
                <a href="?p={{post_list.paginator.num_pages}}" class="primary">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        {% else %}
            <p>No posts yet. <a href="{% url 'social_match:createpost' %}">Create a post.</a></p>
        {% endif %}
    </div>